### ISSUE TITLE
cov2cf return with w/m2

### ISSUE THREAD

**Issue by LiangChen3519** [noctiluc3nt/Reddy#10]
Hi, this is super useful package to play with raw flux data. Thanks for your efforts.
But, when I read the document, I found that, the unit for C flux is W/m2, which is a energy unit, So, I was wondering, which is the right unit after applied the cov2cf function,

Thank you in advance.

**Comment by noctiluc3nt** [comment]
Thank you for your comment.

The units for the flux are like this:
formula: CO2 flux = air density * cov(w,c)
units: kg/(m² s) = kg/m³ m/s kg/kg

So the flux is in the end in kg/(m² s), when you have given c as a mixing ratio [kg/kg] and vertical wind [m/s] and air density [kg/m³]. I updated the documentation accordingly.
